# Site settings
title: SotM LATAM 2016
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://state.osmlatam.org" # the base hostname & protocol for your site
baseurl: /sotm-2016
twitter_username:
github_username:
exclude: [README.md]

# Build settings
markdown: kramdown

# Translations
t:
  en:
    language_name: English
    menu:
      participate:
        label: Participate
        url: /
      venue:
        label: Venue
        url: /venue
      program:
        label: Program
        url: /program
      about:
        label: About
        url: /about
  es:
    language_name: Español
    menu:
      participate:
        label: Participa
        url: /es
      venue:
        label: Local
        url: /es/venue
      program:
        label: Programa
        url: /es/program
      about:
        label: Sobre
        url: /es/about

  pt:
    language_name: Português
    menu:
      participate:
        label: Participe
        url: /pt
      venue:
        label: Local
        url: /pt/venue/
      program:
        label: Programa
        url: /pt/program
      about:
        label: Sobre
        url: /pt/about
