# Site settings
title: State of the Map LATAM 2016
email: info@osmlatam.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
destination: docs
url: "http://state.osmlatam.org" # the base hostname & protocol for your site
baseurl:
twitter_username:
github_username:
exclude: [README.md]

# Build settings
markdown: kramdown

# Translations
t:
  en:
    language_name: English
    menu:
      about:
        label: About
        url: /#about
      program:
        label: Program
        url: /#program
      venue:
        label: Venue
        url: /#venue
      register:
        label: Register
        url: http://www.eventbrite.com/e/state-of-the-map-latam-2016-tickets-27254747684
  es:
    language_name: Español
    menu:
      about:
        label: Sobre
        url: /es/#about
      program:
        label: Programa
        url: /es/#program
      venue:
        label: Local
        url: /es/#venue
      register:
        label: Registrese
        url: http://www.eventbrite.com/e/state-of-the-map-latam-2016-tickets-27254747684
  pt:
    language_name: Português
    menu:
      about:
        label: Sobre
        url: /pt/#about
      program:
        label: Programa
        url: /pt/#program
      venue:
        label: Local
        url: /pt/#venue
      register:
        label: Inscreva-se
        url: http://www.eventbrite.com/e/state-of-the-map-latam-2016-tickets-27254747684
